rock_in_quotes/quotesapp/urls.py
from django.urls import path
from . import views

app_name = 'quotesapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('tag/', views.tag, name='tag'),
    path('quote/', views.quote, name='quote'),
    path('author/', views.author, name='author'),
    path('lookfor/<int:author_id>', views.lookfor, name='lookfor'),
    path('detail/<int:quote_id>', views.detail, name='detail'),
    path('done/<int:quote_id>', views.set_done, name='set_done'),
    path('delete/<int:quote_id>', views.delete_quote, name='delete'),
    path('remove/<int:author_id>', views.remove_author, name='remove')
]

rock_in_quotes/rock_in_quotes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotesapp.urls')),
    path('users/', include('users.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rock_in_quotes/users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import PasswordResetDoneView as prdv
from django.contrib.auth.views import PasswordResetConfirmView as prcv
from django.contrib.auth.views import PasswordResetCompleteView as prcomv


app_name = "users"

urlpatterns = [
    path("signup/", views.signupuser, name="signup"),
    path("login/", views.loginuser, name="login"),
    path("logout/", views.logoutuser, name="logout"),
    path("profile/", views.profile, name="profile"),
    path("reset-password/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        prdv.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        prcv.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        prcomv.as_view(template_name="users/password_reset_complete.html"),
        name="password_reset_complete",
    ),
]

rock_in_quotes/quotesapp/models.py
from django.db import models


class Tag(models.Model):
    name=models.CharField(max_length=50, null=False)
    def __str__(self):
        return f'{self.name}'


    
class Author(models.Model):
    name=models.CharField(max_length=50, null=False)
    borndate=models.DateField()
    bio=models.CharField(max_length=150)

    def __str__(self):
        return f'{self.name}'
    
class Quote(models.Model):
    name=models.CharField(max_length=50, null=False)
    tags=models.ManyToManyField(Tag)
    description=models.CharField(max_length=300)
    done = models.BooleanField(default=False)
    created_date=models.DateTimeField(auto_now_add=True)
    author=models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)

    def __str__(self):
        return f'{self.name}'

rock_in_quotes/quotesapp/forms.py
from django.forms import ModelForm, CharField, DateField, TextInput, DateInput, ModelChoiceField, ModelMultipleChoiceField
from .models import Tag, Quote, Author


class TagForm(ModelForm):

    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())
    
    class Meta:
        model = Tag
        fields = ['name']

class QuoteForm(ModelForm):

    name = CharField(min_length=5, max_length=50, required=True, widget=TextInput())
    description = CharField(min_length=10, max_length=300, required=True, widget=TextInput())
    author = ModelChoiceField(queryset=Author.objects.all())
    tags = ModelMultipleChoiceField(queryset=Tag.objects.all())
    class Meta:
        model = Quote
        fields = ['name', 'description', 'tags', 'author']
        #exclude = ['tags', 'author']

class AuthorForm(ModelForm):

    name = CharField(min_length=5, max_length=50, required=True, widget=TextInput())
    borndate=DateField(widget=DateInput())
    bio = CharField(min_length=10, max_length=150, widget=TextInput())

    class Meta:
        model = Author
        fields = ['name', 'borndate', 'bio']

rock_in_quotes/quotesapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import TagForm, QuoteForm, AuthorForm
from .models import Tag, Quote, Author
from django.contrib.auth.decorators import login_required

# Create your views here.
def main(request):
    quotes = Quote.objects.all()
    authors=Author.objects.all()
    return render(request, 'quotesapp/index.html', {"quotes": quotes, 'authors':authors})

@login_required
def set_done(request, quote_id):
    Quote.objects.filter(pk=quote_id).update(done=True)
    return redirect(to='quotesapp:main')

@login_required
def delete_quote(request, quote_id):
    Quote.objects.get(pk=quote_id).delete()
    return redirect(to='quotesapp:main')

@login_required
def remove_author(request, author_id):
    Author.objects.get(pk=author_id).delete()
    return redirect(to='quotesapp:main')

@login_required
def tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='quotesapp:main')
        else:
            return render(request, 'quotesapp/tag.html', {'form': form})

    return render(request, 'quotesapp/tag.html', {'form': TagForm()})

@login_required
def quote(request):
    tags = Tag.objects.all()
    author=Author.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form
            '''
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)
            
            choice_authors = author.filter(name__in=request.POST.getlist('author')).first()
            new_quote.author=choice_authors.id
            '''
            new_quote.save()

            return redirect(to='quotesapp:main')
        else:
            return render(request, 'quotesapp/quote.html', {"tags": tags, 'author':author, 'form': form})

    return render(request, 'quotesapp/quote.html', {"tags": tags, 'author':author, 'form': QuoteForm()})


def detail(request, quote_id):
    quote = get_object_or_404(Quote, pk=quote_id)
    return render(request, 'quotesapp/detail.html', {"quote": quote})

def lookfor(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, 'quotesapp/lookfor.html', {"author": author})


@login_required
def author(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            author=form
            author.save()

            return redirect(to='quotesapp:main')
        else:
            return render(request, 'quotesapp/author.html', {'form': form})

    return render(request, 'quotesapp/author.html', {'form': AuthorForm()})

rock_in_quotes/quotesapp/templates/quotesapp/author.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:author' %}" style="color: rgba(255, 255, 255, 0.593)">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Author name:
            {{ form.name }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div style="padding: 10px">
        <label> Author borndate:
            {{ form.borndate }}
        </label>
        <span>{{ form.errors.borndate }}</span>
    </div>
    <div style="padding: 10px">
        <label> Author bio:
            {{ form.bio }}
        </label>
        <span>{{ form.errors.bio }}</span>
    </div>
    <div style="padding: 10px">
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

rock_in_quotes/quotesapp/templates/quotesapp/base.html
<!DOCTYPE html>
<html lang="en" style="background-color: rgb(4, 24, 83)">

<head>
    <meta charset="UTF-8" />
    <title>Quote information</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotesapp/style.css' %}">
</head>

<body style="color: rgb(255, 255, 255);">
    <main class="container">
        <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px; color: rgb(255, 255, 255)">
            <ul>
                <li><a href="/" role="button"> Go back to the main page </a></li>
            </ul>
        </nav>
        {% block content %} {% endblock %}
    </main>
</body>

</html>

rock_in_quotes/quotesapp/templates/quotesapp/detail.html
{% extends "quotesapp/base.html" %} {% load extract_tags %} {% block content %}

<h1 style="color: rgb(255, 255, 255);">{{quote.name}}</h1>
<p style="color: rgba(255, 255, 255, 0.593);">Description: <b>{{quote.description}}</b></p>
<p style="color: rgba(255, 255, 255, 0.593);">Time of creation: <kbd>{{quote.created_date}}</kbd></p>
<p style="color: rgba(255, 255, 255, 0.593);">Quote author: <kbd>{{quote.author}}</kbd></p>
{% if quote.done %}
<p style="color: rgba(255, 255, 255, 0.593);">
    Status:
    <ins>Completed</ins>
</p>
{% else %}
<p style="color: rgba(255, 255, 255, 0.593);">Status: <i>Not implemented</i></p>
{% endif %}
<p style="color: rgba(255, 255, 255, 0.593);">Tags: <small> {{ quote.tags|tags }} </small></p>
{% endblock %}

rock_in_quotes/quotesapp/templates/quotesapp/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/modern-normalize/1.0.0/modern-normalize.min.css" />
    <meta charset="UTF-8" />
    <title>Organizer</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css" />
</head>

<body style="background-color: rgb(4, 24, 83); color: rgb(255, 255, 255);">
    <main class="container">
        <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
            {% if user.is_authenticated %}
            <ul>
                <li><a href="{% url 'quotesapp:author' %}" role="button">Add author</a></li>
                <li><a href="{% url 'quotesapp:quote' %}" role="button">Add quote</a></li>
                <li><a href="{% url 'quotesapp:tag' %}" role="button">Add Tag</a></li>
            </ul>
            <ul>
                <li style="color: rgb(255, 255, 255)">Welcome <b>{{ user.username }}!</b></li>
                <li><a href="{% url 'users:profile' %}" role="button">Profile</a></li>
                <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
            {% else %}
            <ul>
                <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
                <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
            </ul>
            {% endif %}
        </nav>
        <h1 style="padding-left: 45%; color: rgb(255, 255, 255)">All quotes</h1>
        {% for quote in quotes %}
        {% if user.is_authenticated %}
        <ul style="padding-left: 35%">
            <li>
                {% if quote.done %}
                <a href="{% url 'quotesapp:detail' quote.id %}" role="button" class="outline" style="background-color: aqua; color: rgb(2, 3, 32)"> {{ quote.name }} </a>
                <a href="{% url 'quotesapp:delete' quote.id %}" role="button" class="contrast"> Delete quote </a>
                {% else %}
                <a href="{% url 'quotesapp:detail' quote.id %}" role="button" class="outline"
                    style="background-color: rgb(183, 61, 244); color: rgb(255, 255, 255)"> {{ quote.name }} </a>
                <a href="{% url 'quotesapp:set_done' quote.id %}" role="button" style="background-color: rgb(64, 0, 255); color: rgb(255, 255, 255)"> Mark Done </a>
                <a href="{% url 'quotesapp:delete' quote.id %}" role="button" class="contrast"> Delete quote </a>
                {% endif %}
            </li>
        </ul>
        {% else %}
        <ul style="padding-left: 45%">
            <li>
                <a href="{% url 'quotesapp:detail' quote.id %}" role="button" class="secondary" style="background-color: aqua; color: rgb(2, 3, 32)">{{ quote.name }}</a>
            </li>
        </ul>
        {% endif %}
        {% endfor %}
        <h1 style="padding-left: 45%; color: rgba(255, 255, 255, 0.836)">All authors</h1>
        {% for author in authors %}
        {% if user.is_authenticated %}
        <ul style="padding-left: 35%">
            <li>
                <a href="{% url 'quotesapp:lookfor' author.id %}" role="button" class="outline" style="background-color: aqua; color: rgb(2, 3, 32)">{{ author.name }}</a>
                <a href="{% url 'quotesapp:remove' author.id %}" role="button" class="contrast"> Delete author </a>
            </li>
        </ul>
        {% else %}
        <ul style="padding-left: 45%">
            <li>
                <a href="{% url 'quotesapp:lookfor' author.id %}" role="button" class="outline" style="background-color: aqua; color: rgb(2, 3, 32)">{{ author.name }}</a>
            </li>
        </ul>
        {% endif %}
        {% endfor %}
    </main>
    <footer style="padding-bottom: 20px; border-bottom: 2px solid; padding-left: 45%">
        <p style="color: rgb(255, 255, 255)">Made by <a href="https://github.com/Sapientus">Sapientus</a></p>
    </footer>
</body>
</html>

rock_in_quotes/quotesapp/templates/quotesapp/lookfor.html
{% extends "quotesapp/base.html" %}{% block content %}

<h1 style="color: rgb(255, 255, 255);">{{author.name}}</h1>
<p style="color: rgba(255, 255, 255, 0.593);">Bio: <b>{{author.bio}}</b></p>
<p style="color: rgba(255, 255, 255, 0.593);">Borndate: <b>{{author.borndate}}</b></p>
{% endblock %}

rock_in_quotes/quotesapp/templates/quotesapp/quote.html
{% extends "quotesapp/base.html" %}{% load extract_tags %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:quote' %}" style="color: rgba(255, 255, 255, 0.593);">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote name:
            {{ form.name }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div style="padding: 10px">
        <label> Quote description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div style="padding: 10px">
        <label> Quote author:
            {{ form.author }}
        </label>
        <span>{{ form.errors.author }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            {{ form.tags }}
        </label>
        <span>{{ form.errors.tags }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

rock_in_quotes/quotesapp/templates/quotesapp/tag.html
{% extends "quotesapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quotesapp:tag' %}" style="color: rgba(255, 255, 255, 0.593)">
    {% csrf_token %}
    <div style="padding: 10px">
        <label>Enter the tag name:
            {{form.name}}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}